# Changes here will be overwritten by Copier
_commit: v0.2.4
_src_path: https://github.com/gookeryoung/coopie
author_email: gooker_young@qq.com
author_name: gooker_young
coverage_fail_under: 95
description: 极速通用文件扫描器.
initial_version: 0.1.0
license: MIT
max_python_version: '3.14'
min_python_version: '3.8'
package_name: uniscan
project_name: uniscan
use_cicd: true
use_cli: true
use_docker: false
use_docs: true
use_domestic_mirrors: true
use_tox: true

