"""GUI 设计令牌集中定义。

按 rule-12-pyside-dev.md 要求，所有 QSS 与代码须引用令牌常量，
禁止散落硬编码颜色/尺寸。QSS 文件通过 ``string.Template`` 引用
``QSS_TOKENS`` 字典中的占位符。

配色沿用现代 GitHub Desktop 风格（扁平、清爽、对比适中），便于后续主题切换。
按钮采用三级层级差异化设计：

* Level 1 主操作（``scan_btn``/``view_results_btn``/``rescan_btn``/``export_btn``）
  - 大尺寸填充或主色边框，强调入口操作
* Level 2 次要操作（``pause_resume_btn``/``cancel_btn``/``select_path_btn``）
  - 中尺寸灰边框，扫描流程与路径选择
* Level 3 辅助操作（详情导航、规则管理、子对话框等）
  - 小尺寸扁平，弱化视觉权重
"""

from __future__ import annotations

__all__ = [
    "COLOR_ACCENT",
    "COLOR_BG_APP",
    "COLOR_BG_CARD",
    "COLOR_BG_HOVER",
    "COLOR_BG_SELECTED",
    "COLOR_BORDER",
    "COLOR_BORDER_MUTED",
    "COLOR_DANGER",
    "COLOR_DANGER_DARK",
    "COLOR_INFO",
    "COLOR_PRIMARY",
    "COLOR_PRIMARY_DARK",
    "COLOR_PRIMARY_DARKER",
    "COLOR_SPLITTER",
    "COLOR_SPLITTER_HOVER",
    "COLOR_TEXT_MUTED",
    "COLOR_TEXT_ON_PRIMARY",
    "COLOR_TEXT_PRIMARY",
    "COLOR_TEXT_SECONDARY",
    "COLOR_WARNING",
    "CONTROL_HEIGHT",
    "BTN_HEIGHT_PRIMARY",
    "BTN_HEIGHT_SECONDARY",
    "BTN_HEIGHT_GHOST",
    "BTN_FONT_PRIMARY",
    "BTN_FONT_SECONDARY",
    "BTN_FONT_GHOST",
    "BTN_PADDING_PRIMARY",
    "BTN_PADDING_SECONDARY",
    "BTN_PADDING_GHOST",
    "BTN_RADIUS_PRIMARY",
    "BTN_RADIUS_SECONDARY",
    "BTN_RADIUS_GHOST",
    "BTN_FONT_WEIGHT",
    "FONT_FAMILY",
    "FONT_FAMILY_MONO",
    "FONT_SIZE_BODY",
    "FONT_SIZE_CAPTION",
    "FONT_SIZE_HEADING",
    "FONT_SIZE_SMALL",
    "FONT_SIZE_TITLE",
    "HEADER_HEIGHT",
    "QSS_TOKENS",
    "RADIUS_LG",
    "RADIUS_MD",
    "RADIUS_SM",
    "SIDEBAR_WIDTH",
    "SPACING_LG",
    "SPACING_MD",
    "SPACING_SM",
    "SPACING_XL",
    "SPACING_XS",
    "STATUSBAR_HEIGHT",
]

# ----------------------------- 色彩令牌 -----------------------------

COLOR_PRIMARY = "#40a9ff"
# 选中态：与 PRIMARY 拉大对比（L*8、a*4），避免视觉上过近
COLOR_PRIMARY_DARK = "#096dd9"
# 按下态：再加一档，与 PRIMARY_DARK 保持可辨层次
COLOR_PRIMARY_DARKER = "#0552a3"
COLOR_ACCENT = "#58a6ff"

COLOR_DANGER = "#d73a49"
COLOR_DANGER_DARK = "#c52332"
COLOR_WARNING = "#f0883e"
COLOR_INFO = "#0366d6"

COLOR_TEXT_PRIMARY = "#24292e"
COLOR_TEXT_SECONDARY = "#586069"
COLOR_TEXT_MUTED = "#959da5"
COLOR_TEXT_ON_PRIMARY = "#ffffff"

COLOR_BG_APP = "#f6f8fa"
COLOR_BG_CARD = "#ffffff"
COLOR_BG_HOVER = "#f6f8fa"
COLOR_BG_SELECTED = "#f1f8ff"

COLOR_BORDER = "#e1e4e8"
COLOR_BORDER_MUTED = "#d0d7de"
# Splitter handle 苍和灰（需求 2）：始终可见但不过分突兀，hover 时加深一档
COLOR_SPLITTER = "#c0c0c0"
COLOR_SPLITTER_HOVER = "#808080"

# ----------------------------- 排版令牌 -----------------------------

FONT_FAMILY = '"Segoe UI", "Microsoft YaHei UI", "Microsoft YaHei", sans-serif'
FONT_FAMILY_MONO = '"Cascadia Code", "Consolas", "Courier New", monospace'
FONT_SIZE_CAPTION = "11px"
FONT_SIZE_SMALL = "12px"
FONT_SIZE_BODY = "13px"
FONT_SIZE_HEADING = "15px"
FONT_SIZE_TITLE = "18px"

# ----------------------------- 间距令牌（8px 基准网格） -----------------------------

SPACING_XS = "4px"
SPACING_SM = "8px"
SPACING_MD = "16px"
SPACING_LG = "24px"
SPACING_XL = "32px"

# ----------------------------- 圆角与尺寸令牌 -----------------------------

RADIUS_SM = "4px"
RADIUS_MD = "6px"
RADIUS_LG = "8px"

HEADER_HEIGHT = "40px"
SIDEBAR_WIDTH = "220px"
STATUSBAR_HEIGHT = "28px"
CONTROL_HEIGHT = "32px"

# ----------------------------- 按钮层级令牌（三级差异化） -----------------------------
#
# 设计意图：主操作大尺寸醒目、次要操作中尺寸常规、辅助操作小尺寸弱化视觉权重。
# QSS 中按 objectName 选择器分别引用以下令牌；minimumSize 在 .ui 中与令牌保持一致。

BTN_HEIGHT_PRIMARY = "48px"
BTN_HEIGHT_SECONDARY = "40px"
BTN_HEIGHT_GHOST = "32px"

BTN_FONT_PRIMARY = FONT_SIZE_HEADING  # 15px
BTN_FONT_SECONDARY = "14px"
BTN_FONT_GHOST = FONT_SIZE_BODY  # 13px

BTN_PADDING_PRIMARY = "12px 28px"
BTN_PADDING_SECONDARY = "8px 20px"
BTN_PADDING_GHOST = "6px 14px"

BTN_RADIUS_PRIMARY = RADIUS_LG  # 8px
BTN_RADIUS_SECONDARY = RADIUS_MD  # 6px
BTN_RADIUS_GHOST = RADIUS_SM  # 4px

BTN_FONT_WEIGHT = "bold"

# ----------------------------- QSS 令牌字典 -----------------------------

QSS_TOKENS: dict[str, str] = {
    "COLOR_PRIMARY": COLOR_PRIMARY,
    "COLOR_PRIMARY_DARK": COLOR_PRIMARY_DARK,
    "COLOR_PRIMARY_DARKER": COLOR_PRIMARY_DARKER,
    "COLOR_ACCENT": COLOR_ACCENT,
    "COLOR_DANGER": COLOR_DANGER,
    "COLOR_DANGER_DARK": COLOR_DANGER_DARK,
    "COLOR_WARNING": COLOR_WARNING,
    "COLOR_INFO": COLOR_INFO,
    "COLOR_TEXT_PRIMARY": COLOR_TEXT_PRIMARY,
    "COLOR_TEXT_SECONDARY": COLOR_TEXT_SECONDARY,
    "COLOR_TEXT_MUTED": COLOR_TEXT_MUTED,
    "COLOR_TEXT_ON_PRIMARY": COLOR_TEXT_ON_PRIMARY,
    "COLOR_BG_APP": COLOR_BG_APP,
    "COLOR_BG_CARD": COLOR_BG_CARD,
    "COLOR_BG_HOVER": COLOR_BG_HOVER,
    "COLOR_BG_SELECTED": COLOR_BG_SELECTED,
    "COLOR_BORDER": COLOR_BORDER,
    "COLOR_BORDER_MUTED": COLOR_BORDER_MUTED,
    "COLOR_SPLITTER": COLOR_SPLITTER,
    "COLOR_SPLITTER_HOVER": COLOR_SPLITTER_HOVER,
    "FONT_FAMILY": FONT_FAMILY,
    "FONT_FAMILY_MONO": FONT_FAMILY_MONO,
    "FONT_SIZE_CAPTION": FONT_SIZE_CAPTION,
    "FONT_SIZE_SMALL": FONT_SIZE_SMALL,
    "FONT_SIZE_BODY": FONT_SIZE_BODY,
    "FONT_SIZE_HEADING": FONT_SIZE_HEADING,
    "FONT_SIZE_TITLE": FONT_SIZE_TITLE,
    "SPACING_XS": SPACING_XS,
    "SPACING_SM": SPACING_SM,
    "SPACING_MD": SPACING_MD,
    "SPACING_LG": SPACING_LG,
    "SPACING_XL": SPACING_XL,
    "RADIUS_SM": RADIUS_SM,
    "RADIUS_MD": RADIUS_MD,
    "RADIUS_LG": RADIUS_LG,
    "HEADER_HEIGHT": HEADER_HEIGHT,
    "SIDEBAR_WIDTH": SIDEBAR_WIDTH,
    "STATUSBAR_HEIGHT": STATUSBAR_HEIGHT,
    "CONTROL_HEIGHT": CONTROL_HEIGHT,
    "BTN_HEIGHT_PRIMARY": BTN_HEIGHT_PRIMARY,
    "BTN_HEIGHT_SECONDARY": BTN_HEIGHT_SECONDARY,
    "BTN_HEIGHT_GHOST": BTN_HEIGHT_GHOST,
    "BTN_FONT_PRIMARY": BTN_FONT_PRIMARY,
    "BTN_FONT_SECONDARY": BTN_FONT_SECONDARY,
    "BTN_FONT_GHOST": BTN_FONT_GHOST,
    "BTN_PADDING_PRIMARY": BTN_PADDING_PRIMARY,
    "BTN_PADDING_SECONDARY": BTN_PADDING_SECONDARY,
    "BTN_PADDING_GHOST": BTN_PADDING_GHOST,
    "BTN_RADIUS_PRIMARY": BTN_RADIUS_PRIMARY,
    "BTN_RADIUS_SECONDARY": BTN_RADIUS_SECONDARY,
    "BTN_RADIUS_GHOST": BTN_RADIUS_GHOST,
    "BTN_FONT_WEIGHT": BTN_FONT_WEIGHT,
}
